spring:
  application:
    name: smart-touch
  datasource:
    url: ${DATABASE_URL}
    username: ${DATABASE_USER}
    password: ${DATABASE_PASS}
    driver-class-name: org.postgresql.Driver
  ai:
    openai:
      api-key: ${OPEN_AI_API_KEY}
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${ASGARDEO_ISSUER_URI}
          jwk-set-uri: ${ASGARDEO_JWK_SET_URI}

smarttouch:
  audience: ${ASGARDEO_CLIENT_ID}

server:
  servlet:
    context-path: /v1
